name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Wait for MySQL service to be ready
    - name: Wait for MySQL
      run: |
        for i in {1..30}; do
          if mysql -h 127.0.0.1 -u test_user -ptest_password -e 'SELECT 1;' test_db; then
            echo "MySQL is ready"
            break
          fi
          echo "Waiting for MySQL to be ready..."
          sleep 1
        done

    # Step 5: Run migrations
    - name: Run migrations
      run: |
        . venv/bin/activate
        python manage.py migrate

    # Step 6: Run tests
    - name: Run tests
      run: |
        . venv/bin/activate
        pytest --junitxml=report.xml
