apiVersion: v1
kind: Service
metadata:
  name: django-messaging-app-service
spec:
  selector:
    app: django-messaging-app  # Select pods with the label app: django-messaging-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000  # The port Django app listens on
  clusterIP: None  # This makes it an internal ClusterIP service
